Rscript MVnorm_IF_unscaled_mixture_control.R P01 > P01.out&
Rscript MVnorm_IF_unscaled_mixture_control.R P02 > P02.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P03 > P03.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P04 > P04.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P05 > P05.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P06 > P06.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P07 > P07.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P08 > P08.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P09 > P09.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P10 > P10.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P11 > P11.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P12 > P12.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P13 > P13.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P14 > P14.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P15 > P15.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P16 > P16.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P17 > P17.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P18 > P18.out&  
Rscript MVnorm_IF_unscaled_mixture_control.R P19 > P19.out&  
